# Generated by Django 5.2.13 on 2026-04-14 15:22

import uuid

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AU", "Australia"),
                            ("CN", "China"),
                            ("DE", "Germany"),
                            ("GB", "United Kingdom"),
                            ("JP", "Japan"),
                            ("TW", "Taiwan"),
                            ("US", "United States"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "reliability_score",
                    models.FloatField(blank=True, help_text="Supplier reliability rating from 0.0 to 5.0.", null=True),
                ),
                (
                    "typical_lead_days",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Typical lead time from order to delivery, in days.", null=True
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True,
                        help_text="Approval status: null = under review, true = approved, false = rejected.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("address", models.TextField()),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "id"],
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.AddField(
            model_name="widget",
            name="datasheet",
            field=models.FileField(blank=True, null=True, upload_to="widgets/datasheets/"),
        ),
        migrations.AddField(
            model_name="widget",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="widgets/images/"),
        ),
        migrations.AddField(
            model_name="widget",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="specifications",
            field=models.JSONField(blank=True, default=dict, help_text="Arbitrary key-value specification data."),
        ),
        migrations.AddField(
            model_name="widget",
            name="warranty_period",
            field=models.DurationField(
                blank=True, help_text="Duration of the product warranty, e.g. 365 days.", null=True
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("discount_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("valid_dates", django.contrib.postgres.fields.ranges.DateRangeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("widgets", models.ManyToManyField(blank=True, related_name="promotions", to="catalog.widget")),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.AddField(
            model_name="widget",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widgets",
                to="catalog.supplier",
            ),
        ),
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
                (
                    "reorder_threshold",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Reorder stock when quantity on hand falls below this level."
                    ),
                ),
                (
                    "max_stock_level",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum stock level to hold at this location.", null=True
                    ),
                ),
                ("last_stocktake_at", models.DateTimeField(blank=True, null=True)),
                ("last_received_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="catalog.widgetvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="catalog.warehouse"
                    ),
                ),
            ],
            options={
                "ordering": ["warehouse", "variant"],
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("variant", "warehouse"), name="unique_inventory_per_variant_warehouse"
                    )
                ],
            },
        ),
    ]
