# Generated by Django 5.2.14 on 2026-08-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_supplier_warehouse_widget_datasheet_widget_image_and_more"),
    ]

    operations = [
        # State-only realignment: the earlier migrations recorded ordering as lists while
        # the models declare tuples, so makemigrations reported these seven models as
        # changed on every run. No SQL, no permission changes.
        migrations.AlterModelOptions(
            name="inventoryrecord",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ("warehouse", "variant"),
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"default_permissions": ("create", "read", "update", "delete", "list"), "ordering": ("name", "id")},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"default_permissions": ("create", "read", "update", "delete", "list"), "ordering": ("name", "id")},
        ),
        migrations.AlterModelOptions(
            name="widget",
            options={"default_permissions": ("create", "read", "update", "delete", "list"), "ordering": ("name", "id")},
        ),
        migrations.AlterModelOptions(
            name="widgetcategory",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ("name", "id"),
                "verbose_name_plural": "widget categories",
            },
        ),
        migrations.AlterModelOptions(
            name="widgetvariant",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ("widget", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reference",
                    models.CharField(help_text="Purchase order number, e.g. PO-1042.", max_length=32, unique=True),
                ),
                ("order_date", models.DateField(help_text="Date the order was placed with the supplier.")),
                (
                    "expected_arrival_date",
                    models.DateField(
                        blank=True, help_text="Date the supplier expects to deliver the order.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        help_text="Warehouse the ordered stock is delivered to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_purchase_orders",
                        to="catalog.warehouse",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="catalog.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("-order_date", "-reference"),
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_ordered", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price agreed with the supplier, which may differ from the widget's list price.",
                        max_digits=10,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="catalog.purchaseorder"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="catalog.widgetvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("purchase_order", "id"),
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
