# Generated by Django 5.2.14 on 2026-08-25 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_purchaseorder_purchaseorderline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ("-order_date", "-reference"),
                "permissions": (
                    ("submit_purchaseorder", "Can submit purchase orders for approval"),
                    ("approve_purchaseorder", "Can approve submitted purchase orders"),
                    ("reject_purchaseorder", "Can reject submitted purchase orders back to draft"),
                    ("receive_purchaseorder", "Can receive approved purchase orders into a warehouse"),
                    ("cancel_purchaseorder", "Can cancel purchase orders"),
                ),
            },
        ),
    ]
