# Generated by Django 5.2.14 on 2026-09-14 21:15

import uuid

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_purchaseorder_options"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryRecordEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
                (
                    "reorder_threshold",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Reorder stock when quantity on hand falls below this level."
                    ),
                ),
                (
                    "max_stock_level",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum stock level to hold at this location.", null=True
                    ),
                ),
                ("last_stocktake_at", models.DateTimeField(blank=True, null=True)),
                ("last_received_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromotionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("discount_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("valid_dates", django.contrib.postgres.fields.ranges.DateRangeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("reference", models.CharField(help_text="Purchase order number, e.g. PO-1042.", max_length=32)),
                ("order_date", models.DateField(help_text="Date the order was placed with the supplier.")),
                (
                    "expected_arrival_date",
                    models.DateField(
                        blank=True, help_text="Date the supplier expects to deliver the order.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLineEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("quantity_ordered", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price agreed with the supplier, which may differ from the widget's list price.",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(db_index=False, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AU", "Australia"),
                            ("CN", "China"),
                            ("DE", "Germany"),
                            ("GB", "United Kingdom"),
                            ("JP", "Japan"),
                            ("TW", "Taiwan"),
                            ("US", "United States"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "reliability_score",
                    models.FloatField(blank=True, help_text="Supplier reliability rating from 0.0 to 5.0.", null=True),
                ),
                (
                    "typical_lead_days",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Typical lead time from order to delivery, in days.", null=True
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True,
                        help_text="Approval status: null = under review, true = approved, false = rejected.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarehouseEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=32)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("address", models.TextField()),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WidgetCategoryEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WidgetEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, db_index=False, max_length=100, null=True)),
                ("sku", models.CharField(max_length=64, verbose_name="SKU")),
                ("description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "warranty_period",
                    models.DurationField(
                        blank=True, help_text="Duration of the product warranty, e.g. 365 days.", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="widgets/images/")),
                ("datasheet", models.FileField(blank=True, null=True, upload_to="widgets/datasheets/")),
                (
                    "specifications",
                    models.JSONField(blank=True, default=dict, help_text="Arbitrary key-value specification data."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WidgetVariantEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku_suffix", models.CharField(max_length=32)),
                ("additional_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_inventoryrecordevent" ("id", "last_received_at", "last_stocktake_at", "max_stock_level", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity_on_hand", "reorder_threshold", "variant_id", "warehouse_id") VALUES (NEW."id", NEW."last_received_at", NEW."last_stocktake_at", NEW."max_stock_level", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."quantity_on_hand", NEW."reorder_threshold", NEW."variant_id", NEW."warehouse_id"); RETURN NULL;',
                    hash="308c2ff57915ab81a64cdb6ac5a218437fddbe0d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3a705",
                    table="catalog_inventoryrecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_inventoryrecordevent" ("id", "last_received_at", "last_stocktake_at", "max_stock_level", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity_on_hand", "reorder_threshold", "variant_id", "warehouse_id") VALUES (NEW."id", NEW."last_received_at", NEW."last_stocktake_at", NEW."max_stock_level", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."quantity_on_hand", NEW."reorder_threshold", NEW."variant_id", NEW."warehouse_id"); RETURN NULL;',
                    hash="bb15977d7e24608442fb5cb525ba6eb615f48ba8",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_dd4b6",
                    table="catalog_inventoryrecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_inventoryrecordevent" ("id", "last_received_at", "last_stocktake_at", "max_stock_level", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity_on_hand", "reorder_threshold", "variant_id", "warehouse_id") VALUES (OLD."id", OLD."last_received_at", OLD."last_stocktake_at", OLD."max_stock_level", OLD."notes", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."quantity_on_hand", OLD."reorder_threshold", OLD."variant_id", OLD."warehouse_id"); RETURN NULL;',
                    hash="d6a6722bad205d281c565bda58ec77f16a2f96d9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_57e95",
                    table="catalog_inventoryrecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="promotion",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_promotionevent" ("code", "created_at", "description", "discount_percent", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "valid_dates") VALUES (NEW."code", NEW."created_at", NEW."description", NEW."discount_percent", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."valid_dates"); RETURN NULL;',
                    hash="d463a0f3cd230b863d2bac6595b7f91e5644896c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_d7615",
                    table="catalog_promotion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="promotion",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_promotionevent" ("code", "created_at", "description", "discount_percent", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "valid_dates") VALUES (NEW."code", NEW."created_at", NEW."description", NEW."discount_percent", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."valid_dates"); RETURN NULL;',
                    hash="c0ae1e6e9abd7e673458917d2054dbf9ef1bc00e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8abc2",
                    table="catalog_promotion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="promotion",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_promotionevent" ("code", "created_at", "description", "discount_percent", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "valid_dates") VALUES (OLD."code", OLD."created_at", OLD."description", OLD."discount_percent", OLD."id", OLD."is_active", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."valid_dates"); RETURN NULL;',
                    hash="16aceb2a60c37381c4e087f74c1ab6b5cf8f89e7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_7609c",
                    table="catalog_promotion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorder",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_purchaseorderevent" ("created_at", "destination_warehouse_id", "expected_arrival_date", "id", "order_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "supplier_id", "updated_at") VALUES (NEW."created_at", NEW."destination_warehouse_id", NEW."expected_arrival_date", NEW."id", NEW."order_date", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."reference", NEW."supplier_id", NEW."updated_at"); RETURN NULL;',
                    hash="e601c09c7c5f7b6d94194dcb119a404fc2913b5f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_0c501",
                    table="catalog_purchaseorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorder",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_purchaseorderevent" ("created_at", "destination_warehouse_id", "expected_arrival_date", "id", "order_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "supplier_id", "updated_at") VALUES (NEW."created_at", NEW."destination_warehouse_id", NEW."expected_arrival_date", NEW."id", NEW."order_date", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."reference", NEW."supplier_id", NEW."updated_at"); RETURN NULL;',
                    hash="f624603c2a8a2b1971e752e03ea2393a91d73f72",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_4903a",
                    table="catalog_purchaseorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorder",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_purchaseorderevent" ("created_at", "destination_warehouse_id", "expected_arrival_date", "id", "order_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "supplier_id", "updated_at") VALUES (OLD."created_at", OLD."destination_warehouse_id", OLD."expected_arrival_date", OLD."id", OLD."order_date", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."reference", OLD."supplier_id", OLD."updated_at"); RETURN NULL;',
                    hash="5aa0e474320a098b822d06cbf7828c7c7f161732",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_06645",
                    table="catalog_purchaseorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorderline",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_purchaseorderlineevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purchase_order_id", "quantity_ordered", "unit_price", "variant_id") VALUES (NEW."id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."purchase_order_id", NEW."quantity_ordered", NEW."unit_price", NEW."variant_id"); RETURN NULL;',
                    hash="a47f7164c04cd8e33c626aefd9b8d1389fd8c17f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_20547",
                    table="catalog_purchaseorderline",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorderline",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_purchaseorderlineevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purchase_order_id", "quantity_ordered", "unit_price", "variant_id") VALUES (NEW."id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."purchase_order_id", NEW."quantity_ordered", NEW."unit_price", NEW."variant_id"); RETURN NULL;',
                    hash="cf922d4dc63899f18636face23460917cf13ab24",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_52561",
                    table="catalog_purchaseorderline",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorderline",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_purchaseorderlineevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purchase_order_id", "quantity_ordered", "unit_price", "variant_id") VALUES (OLD."id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."purchase_order_id", OLD."quantity_ordered", OLD."unit_price", OLD."variant_id"); RETURN NULL;',
                    hash="09e98b7746c165996aed789d1fe96a0173f9af15",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_c8847",
                    table="catalog_purchaseorderline",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplier",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_supplierevent" ("contact_email", "country", "created_at", "id", "is_active", "is_approved", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reliability_score", "slug", "typical_lead_days", "updated_at", "website") VALUES (NEW."contact_email", NEW."country", NEW."created_at", NEW."id", NEW."is_active", NEW."is_approved", NEW."name", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."reliability_score", NEW."slug", NEW."typical_lead_days", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="f02fdc90867c5c43b5d25c182716694ea811566f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_c6c3c",
                    table="catalog_supplier",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplier",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_supplierevent" ("contact_email", "country", "created_at", "id", "is_active", "is_approved", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reliability_score", "slug", "typical_lead_days", "updated_at", "website") VALUES (NEW."contact_email", NEW."country", NEW."created_at", NEW."id", NEW."is_active", NEW."is_approved", NEW."name", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."reliability_score", NEW."slug", NEW."typical_lead_days", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="f185ecb5d6c41bcd63dad28bccaf88c2bdbf71cf",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_9b06a",
                    table="catalog_supplier",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplier",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_supplierevent" ("contact_email", "country", "created_at", "id", "is_active", "is_approved", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reliability_score", "slug", "typical_lead_days", "updated_at", "website") VALUES (OLD."contact_email", OLD."country", OLD."created_at", OLD."id", OLD."is_active", OLD."is_approved", OLD."name", OLD."notes", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."reliability_score", OLD."slug", OLD."typical_lead_days", OLD."updated_at", OLD."website"); RETURN NULL;',
                    hash="2d83e6900d3644b9f0224744dcf58d78e3971c90",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_2689e",
                    table="catalog_supplier",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="warehouse",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_warehouseevent" ("address", "closes_at", "code", "contact_email", "id", "is_active", "name", "opens_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (NEW."address", NEW."closes_at", NEW."code", NEW."contact_email", NEW."id", NEW."is_active", NEW."name", NEW."opens_at", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."uuid"); RETURN NULL;',
                    hash="38dc38677047cc54619e43a91e079e854b685832",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_8cf3c",
                    table="catalog_warehouse",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="warehouse",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_warehouseevent" ("address", "closes_at", "code", "contact_email", "id", "is_active", "name", "opens_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (NEW."address", NEW."closes_at", NEW."code", NEW."contact_email", NEW."id", NEW."is_active", NEW."name", NEW."opens_at", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."uuid"); RETURN NULL;',
                    hash="5dbb91b5dc90ea0413b97cf701182edda1da4325",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a584a",
                    table="catalog_warehouse",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="warehouse",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_warehouseevent" ("address", "closes_at", "code", "contact_email", "id", "is_active", "name", "opens_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "uuid") VALUES (OLD."address", OLD."closes_at", OLD."code", OLD."contact_email", OLD."id", OLD."is_active", OLD."name", OLD."opens_at", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."uuid"); RETURN NULL;',
                    hash="c942d38ab03d20a34b8081457457b89f7ac81377",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_0301d",
                    table="catalog_warehouse",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widget",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_widgetevent" ("category_id", "created_at", "datasheet", "description", "id", "image", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "release_date", "sku", "slug", "specifications", "supplier_id", "unit_price", "updated_at", "warranty_period", "weight_kg") VALUES (NEW."category_id", NEW."created_at", NEW."datasheet", NEW."description", NEW."id", NEW."image", NEW."is_active", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."release_date", NEW."sku", NEW."slug", NEW."specifications", NEW."supplier_id", NEW."unit_price", NEW."updated_at", NEW."warranty_period", NEW."weight_kg"); RETURN NULL;',
                    hash="781c336b03f918d1ec8da04644297f701afab669",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_db917",
                    table="catalog_widget",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widget",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_widgetevent" ("category_id", "created_at", "datasheet", "description", "id", "image", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "release_date", "sku", "slug", "specifications", "supplier_id", "unit_price", "updated_at", "warranty_period", "weight_kg") VALUES (NEW."category_id", NEW."created_at", NEW."datasheet", NEW."description", NEW."id", NEW."image", NEW."is_active", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."release_date", NEW."sku", NEW."slug", NEW."specifications", NEW."supplier_id", NEW."unit_price", NEW."updated_at", NEW."warranty_period", NEW."weight_kg"); RETURN NULL;',
                    hash="970b55678cd6acaf771a38873d68efb9edf0d3d8",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c78f3",
                    table="catalog_widget",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widget",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_widgetevent" ("category_id", "created_at", "datasheet", "description", "id", "image", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "release_date", "sku", "slug", "specifications", "supplier_id", "unit_price", "updated_at", "warranty_period", "weight_kg") VALUES (OLD."category_id", OLD."created_at", OLD."datasheet", OLD."description", OLD."id", OLD."image", OLD."is_active", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."release_date", OLD."sku", OLD."slug", OLD."specifications", OLD."supplier_id", OLD."unit_price", OLD."updated_at", OLD."warranty_period", OLD."weight_kg"); RETURN NULL;',
                    hash="46e4e09a4226fde477ad3845be40e3c121e47c2c",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_1ec53",
                    table="catalog_widget",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_widgetcategoryevent" ("code", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."code", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="664bd65d4b9adfdcc92663f39c4bf4bb9b810aa2",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a647f",
                    table="catalog_widgetcategory",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_widgetcategoryevent" ("code", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."code", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id"); RETURN NULL;',
                    hash="92289f1ac85c1bf605148b896548c9255163a011",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_48d8a",
                    table="catalog_widgetcategory",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_widgetcategoryevent" ("code", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."code", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="7d8dd53ab122aeb3dbaf7063b831ddc86719d48f",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_b03b4",
                    table="catalog_widgetcategory",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetvariant",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_widgetvariantevent" ("additional_price", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sku_suffix", "stock_quantity", "widget_id") VALUES (NEW."additional_price", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."sku_suffix", NEW."stock_quantity", NEW."widget_id"); RETURN NULL;',
                    hash="10fff549517a00a0921c352d88a2af0d489164f4",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_1c9fd",
                    table="catalog_widgetvariant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetvariant",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_widgetvariantevent" ("additional_price", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sku_suffix", "stock_quantity", "widget_id") VALUES (NEW."additional_price", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."sku_suffix", NEW."stock_quantity", NEW."widget_id"); RETURN NULL;',
                    hash="e520671d137e2c0096b36295fc32145f827f1b32",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_49d54",
                    table="catalog_widgetvariant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetvariant",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_widgetvariantevent" ("additional_price", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sku_suffix", "stock_quantity", "widget_id") VALUES (OLD."additional_price", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."sku_suffix", OLD."stock_quantity", OLD."widget_id"); RETURN NULL;',
                    hash="a73186f1817538f81f870b7fcc0045ef2e668fbe",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_64a24",
                    table="catalog_widgetvariant",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecordevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecordevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.inventoryrecord",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecordevent",
            name="variant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.widgetvariant",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecordevent",
            name="warehouse",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="promotionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="promotionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.promotion",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderevent",
            name="destination_warehouse",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Warehouse the ordered stock is delivered to.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderevent",
            name="supplier",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineevent",
            name="purchase_order",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineevent",
            name="variant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.widgetvariant",
            ),
        ),
        migrations.AddField(
            model_name="supplierevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="supplierevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.supplier",
            ),
        ),
        migrations.AddField(
            model_name="warehouseevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="warehouseevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="widgetcategoryevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="widgetcategoryevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.widgetcategory",
            ),
        ),
        migrations.AddField(
            model_name="widgetevent",
            name="category",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.widgetcategory",
            ),
        ),
        migrations.AddField(
            model_name="widgetevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="widgetevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.widget",
            ),
        ),
        migrations.AddField(
            model_name="widgetevent",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.supplier",
            ),
        ),
        migrations.AddField(
            model_name="widgetvariantevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="widgetvariantevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.widgetvariant",
            ),
        ),
        migrations.AddField(
            model_name="widgetvariantevent",
            name="widget",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.widget",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecordevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="382cdb15bb8b50a502f2b8898dac7560d804631f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_af1c7",
                    table="catalog_inventoryrecordevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="promotionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a65f198144cefe2d140ea8d29c3593e0e324f8f2",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_13ccc",
                    table="catalog_promotionevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorderevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="0ec9e9645bb500d4df547ff5f7aefaca0201e59a",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d7f74",
                    table="catalog_purchaseorderevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorderlineevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="158ecff3b437e0d63d928dbdf5b82f545dee971d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_eed42",
                    table="catalog_purchaseorderlineevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplierevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="948a1c23bccbd4797dd507dd21a6bf0d5b7563fc",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_c61d2",
                    table="catalog_supplierevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="warehouseevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="bdd873a510242a43649e985e280c011debb3b3b9",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_09c6c",
                    table="catalog_warehouseevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetcategoryevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="574336dab00beb83ffadf0ede892343caf03876f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d5acf",
                    table="catalog_widgetcategoryevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="e3a4d362b7e36c57d01817158a6be18281f313c3",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_c9718",
                    table="catalog_widgetevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="widgetvariantevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="0ad330e81113d31cf88b8864997fce43e583816d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_736a3",
                    table="catalog_widgetvariantevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
