# Generated by Django 6.1.1 on 2026-09-19 03:17

import django.contrib.postgres.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_inventoryrecordevent_promotionevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="supplier",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="supplier",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="supplier",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="supplier",
            name="notification_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                help_text="Additional addresses copied on purchase orders sent to this supplier.",
            ),
        ),
        migrations.AddField(
            model_name="supplierevent",
            name="notification_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                help_text="Additional addresses copied on purchase orders sent to this supplier.",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplier",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_supplierevent" ("contact_email", "country", "created_at", "id", "is_active", "is_approved", "name", "notes", "notification_emails", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reliability_score", "slug", "typical_lead_days", "updated_at", "website") VALUES (NEW."contact_email", NEW."country", NEW."created_at", NEW."id", NEW."is_active", NEW."is_approved", NEW."name", NEW."notes", NEW."notification_emails", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."reliability_score", NEW."slug", NEW."typical_lead_days", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="459c7ff28910a7390276687d2a301ae6f936caf7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_c6c3c",
                    table="catalog_supplier",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplier",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_supplierevent" ("contact_email", "country", "created_at", "id", "is_active", "is_approved", "name", "notes", "notification_emails", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reliability_score", "slug", "typical_lead_days", "updated_at", "website") VALUES (NEW."contact_email", NEW."country", NEW."created_at", NEW."id", NEW."is_active", NEW."is_approved", NEW."name", NEW."notes", NEW."notification_emails", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."reliability_score", NEW."slug", NEW."typical_lead_days", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="841007e424e8b850612390760e56669f6b44c8e9",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_9b06a",
                    table="catalog_supplier",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplier",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_supplierevent" ("contact_email", "country", "created_at", "id", "is_active", "is_approved", "name", "notes", "notification_emails", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reliability_score", "slug", "typical_lead_days", "updated_at", "website") VALUES (OLD."contact_email", OLD."country", OLD."created_at", OLD."id", OLD."is_active", OLD."is_approved", OLD."name", OLD."notes", OLD."notification_emails", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."reliability_score", OLD."slug", OLD."typical_lead_days", OLD."updated_at", OLD."website"); RETURN NULL;',
                    hash="5513f0ebd8f939beab4c80e6f29ced2e87b9a83f",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_2689e",
                    table="catalog_supplier",
                    when="AFTER",
                ),
            ),
        ),
    ]
