# Generated by Django 6.1.1 on 2026-09-19 04:58
# Modified using django-view-manager 2.0.0.  Please do not delete this comment.
import os

from django.db import migrations

sql_path = "widget_warehouse/catalog/sql"
forward_sql_filename = "view-catalog_purchaseorderstatecount-latest.sql"

with open(os.path.join(sql_path, forward_sql_filename)) as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):
    # makeviewmigration cannot know what the SQL references, so the cross-app dependencies
    # are added by hand. The view reads vueda_workflow's state, workflow, and object state
    # tables, all created in that app's initial migration, and resolves the workflow
    # through django_content_type. Without these, a database built from scratch runs this
    # before those tables exist; an already-migrated database hides the problem.
    dependencies = [
        ("catalog", "0006_remove_supplier_insert_insert_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("vueda_workflow", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS catalog_purchaseorderstatecount;",
        ),
    ]
