# Generated by Django 6.1.1 on 2026-09-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_create_order_state_count_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderStateCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Order to display the states in, following the workflow rather than the alphabet."
                    ),
                ),
                ("order_count", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "purchase order state count",
                "db_table": "catalog_purchaseorderstatecount",
                "ordering": ("position", "id"),
                "managed": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
