# Generated by Django 6.1.1 on 2026-09-20 22:24

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_purchaseorderstatecount"),
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplenishmentBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_digest", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
            ],
            options={
                "ordering": ("supplier", "variant"),
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="SupplierPriceEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryrecord",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ("warehouse", "variant"),
                "permissions": (("replenish_inventoryrecord", "Can replenish inventory with draft purchase orders"),),
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="purchaseorder",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="purchaseorder",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="purchaseorder",
            name="delete_delete",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorder",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_purchaseorderevent" ("created_at", "destination_warehouse_id", "expected_arrival_date", "id", "order_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "replenishment_batch_id", "supplier_id", "updated_at") VALUES (NEW."created_at", NEW."destination_warehouse_id", NEW."expected_arrival_date", NEW."id", NEW."order_date", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."reference", NEW."replenishment_batch_id", NEW."supplier_id", NEW."updated_at"); RETURN NULL;',
                    hash="ec29930a7e16e10ef401095efd81c5e6796ce849",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_0c501",
                    table="catalog_purchaseorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorder",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_purchaseorderevent" ("created_at", "destination_warehouse_id", "expected_arrival_date", "id", "order_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "replenishment_batch_id", "supplier_id", "updated_at") VALUES (NEW."created_at", NEW."destination_warehouse_id", NEW."expected_arrival_date", NEW."id", NEW."order_date", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."reference", NEW."replenishment_batch_id", NEW."supplier_id", NEW."updated_at"); RETURN NULL;',
                    hash="20c2db983e97b62267050e905da9b8357f12d322",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_4903a",
                    table="catalog_purchaseorder",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="purchaseorder",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_purchaseorderevent" ("created_at", "destination_warehouse_id", "expected_arrival_date", "id", "order_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "replenishment_batch_id", "supplier_id", "updated_at") VALUES (OLD."created_at", OLD."destination_warehouse_id", OLD."expected_arrival_date", OLD."id", OLD."order_date", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."reference", OLD."replenishment_batch_id", OLD."supplier_id", OLD."updated_at"); RETURN NULL;',
                    hash="a07de46994ee32daee8894a68e92866eec08fffd",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_06645",
                    table="catalog_purchaseorder",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="replenishmentbatch",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="replenishment_batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="catalog.replenishmentbatch",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderevent",
            name="replenishment_batch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.replenishmentbatch",
            ),
        ),
        migrations.AddField(
            model_name="supplierprice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="catalog.supplier"
            ),
        ),
        migrations.AddField(
            model_name="supplierprice",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="supplier_prices", to="catalog.widgetvariant"
            ),
        ),
        migrations.AddField(
            model_name="supplierpriceevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="supplierpriceevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="catalog.supplierprice",
            ),
        ),
        migrations.AddField(
            model_name="supplierpriceevent",
            name="supplier",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.supplier",
            ),
        ),
        migrations.AddField(
            model_name="supplierpriceevent",
            name="variant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="catalog.widgetvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierprice",
            constraint=models.UniqueConstraint(fields=("supplier", "variant"), name="unique_supplier_variant_price"),
        ),
        migrations.AddConstraint(
            model_name="supplierprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)), name="supplier_cost_nonnegative"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplierprice",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_supplierpriceevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supplier_id", "unit_cost", "variant_id") VALUES (NEW."id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."supplier_id", NEW."unit_cost", NEW."variant_id"); RETURN NULL;',
                    hash="38f0def57aa0eff6e62b7104034129e89cd28c5c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_b9a2c",
                    table="catalog_supplierprice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplierprice",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_supplierpriceevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supplier_id", "unit_cost", "variant_id") VALUES (NEW."id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."supplier_id", NEW."unit_cost", NEW."variant_id"); RETURN NULL;',
                    hash="a650d61a819203419db4456dde85f4c46eda7a0b",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a6efb",
                    table="catalog_supplierprice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplierprice",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_supplierpriceevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supplier_id", "unit_cost", "variant_id") VALUES (OLD."id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."supplier_id", OLD."unit_cost", OLD."variant_id"); RETURN NULL;',
                    hash="605e126da19cd34a673ca54696200623f7b4e5f5",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_274ff",
                    table="catalog_supplierprice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="supplierpriceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="076049cbbe01f3d97c85c6309ebb522636cd75c5",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_cbcd4",
                    table="catalog_supplierpriceevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
