# Generated by Django 6.1.1 on 2026-09-20 22:39

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_replenishmentbatch_supplierprice_supplierpriceevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="inventoryrecord",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="inventoryrecord",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="inventoryrecord",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="replenishment_revision",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="inventoryrecordevent",
            name="replenishment_revision",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_inventoryrecordevent" ("id", "last_received_at", "last_stocktake_at", "max_stock_level", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity_on_hand", "reorder_threshold", "replenishment_revision", "variant_id", "warehouse_id") VALUES (NEW."id", NEW."last_received_at", NEW."last_stocktake_at", NEW."max_stock_level", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."quantity_on_hand", NEW."reorder_threshold", NEW."replenishment_revision", NEW."variant_id", NEW."warehouse_id"); RETURN NULL;',
                    hash="6b277da07c2e92bb2fd5320dfbad4ba721627274",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3a705",
                    table="catalog_inventoryrecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "catalog_inventoryrecordevent" ("id", "last_received_at", "last_stocktake_at", "max_stock_level", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity_on_hand", "reorder_threshold", "replenishment_revision", "variant_id", "warehouse_id") VALUES (NEW."id", NEW."last_received_at", NEW."last_stocktake_at", NEW."max_stock_level", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."quantity_on_hand", NEW."reorder_threshold", NEW."replenishment_revision", NEW."variant_id", NEW."warehouse_id"); RETURN NULL;',
                    hash="2c003c3df66d1979fac786a6b1006160d7eef15b",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_dd4b6",
                    table="catalog_inventoryrecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="inventoryrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "catalog_inventoryrecordevent" ("id", "last_received_at", "last_stocktake_at", "max_stock_level", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity_on_hand", "reorder_threshold", "replenishment_revision", "variant_id", "warehouse_id") VALUES (OLD."id", OLD."last_received_at", OLD."last_stocktake_at", OLD."max_stock_level", OLD."notes", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."quantity_on_hand", OLD."reorder_threshold", OLD."replenishment_revision", OLD."variant_id", OLD."warehouse_id"); RETURN NULL;',
                    hash="7d79b94247ad36ffd039cf254bc2e865c6164fd9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_57e95",
                    table="catalog_inventoryrecord",
                    when="AFTER",
                ),
            ),
        ),
    ]
